export const FEEDBACK_REQUEST = "FEEDBACK_REQUEST"
export const POST_FEEDBACK_SUCCESS = "POST_FEEDBACK_SUCCESS"
export const FEEDBACK_FAIL = "FEEDBACK_FAIL"


export const GET_FEEDBACK_SUCCESS = "GET_FEEDBACK_SUCCESS"
